version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=my_database
      - MYSQL_ROOT_PASSWORD=example  # ルートユーザーのパスワードを設定する
      - TZ=Asia/Tokyo
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 23306:3306
